interval: 120

messages:
  1:
    message: "&8» &6Milo cie tu goscic!"

  2:
    message: "&8» &6Sprawdz mojego githuba! &7(KLIK)"
    type: OpenWeb
    action: "https://github.com/Osnixeroo/"
    hover: "&7Kliknij aby przejsc na: &ehttps://github.com/Osnixeroo/"

  3:
    message: "&8» &6Sprawdz aktualne pluginy! &7(KLIK)"
    type: RunCommand
    action: "/plugins"
    hover: "&7Kliknij aby wykonac komende: &e/plugins"
